FROM node:16
RUN mkdir -p /home/app/node_modules && chown -R node:node /home/app
WORKDIR /home/app
COPY --chown=node:node package*.json ./
COPY --chown=node:node tsconfig*.json ./
USER node
RUN npm install
COPY --chown=node:node ./ ./
EXPOSE 3000
RUN npm run ts:prod
CMD [ "npm", "run", "start" ]