FROM node:16
WORKDIR /app
COPY --chown=node:node package*.json /app
COPY --chown=node:node tsconfig*.json /app
USER node
RUN npm install
COPY --chown=node:node . /app
EXPOSE 3000
RUN npm run ts:prod
CMD [ "npm", "start" ]